@extends('layouts.app')

@section('title', 'AI SEO Auditor - Terms of Service')

@section('content')
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-24">
    <div class="mb-12">
        <h1 class="text-4xl md:text-5xl font-extrabold mb-4 text-white">Terms of Service</h1>
        <p class="text-slate-400">Last updated: {{ date('F j, Y') }}</p>
    </div>

    <div class="prose prose-invert prose-indigo max-w-none text-slate-300">
        <h2 class="text-2xl font-bold text-white mt-8 mb-4">1. Acceptance of Terms</h2>
        <p>By accessing or using the AI SEO Auditor platform, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you may not access the service.</p>

        <h2 class="text-2xl font-bold text-white mt-8 mb-4">2. Use of Service</h2>
        <p>Our service provides real-time SEO analysis using Google Gemini AI. You agree to use this service only for lawful purposes and in a way that does not infringe the rights of, restrict, or inhibit anyone else's use and enjoyment of the website.</p>
        <p>You may not use our crawler to target websites with malicious intent, execute denial of service (DoS) attacks, or violate the target website's terms of service.</p>

        <h2 class="text-2xl font-bold text-white mt-8 mb-4">3. AI-Generated Content</h2>
        <p>The SEO recommendations and reports generated by our platform are powered by Artificial Intelligence (Google Gemini). While we strive for high accuracy, the reports are provided "as is" without any guarantees of exact ranking improvements. You are responsible for verifying any critical changes before implementing them on your production environments.</p>

        <h2 class="text-2xl font-bold text-white mt-8 mb-4">4. Intellectual Property</h2>
        <p>The Service and its original content, features, and functionality are and will remain the exclusive property of AI SEO Auditor and its licensors. Our branding, logo, and generated PDF formats are protected by copyright, trademark, and other laws.</p>

        <h2 class="text-2xl font-bold text-white mt-8 mb-4">5. Limitation of Liability</h2>
        <p>In no event shall AI SEO Auditor, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

        <h2 class="text-2xl font-bold text-white mt-8 mb-4">6. Changes to Terms</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide at least 30 days notice prior to any new terms taking effect.</p>
    </div>
</div>
@endsection
